#!/usr/bin/env python
#
# Copyright 2017 Fraunhofer Institute for Manufacturing Engineering and Automation (IPA)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


import rospy
import rosservice

if __name__ == "__main__":
    argv = rospy.myargv()
    if len(argv) != 3:
        rospy.logerr("service_relay IN OUT")

    rospy.init_node("service_relay")

    local_name, remote_name = argv[1], argv[2]

    rospy.wait_for_service(remote_name)
    srv_def = rosservice.get_service_class_by_name(remote_name)
    remote = rospy.ServiceProxy(remote_name, srv_def)

    local = rospy.Service(local_name,srv_def, remote.call)
    rospy.loginfo("Started relay from %s to %s (%s)" % (local_name, remote_name, srv_def._type))
    rospy.spin()
