local_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 4.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.025
  origin_x: 0.0
  origin_y: 0.0