generic_throttle:
  namespace: debug # namespace for republished topics
  topic_framerate: #[topic_name, max_framerate]
    - [/torso_cam3d_left/rgb/image_raw, 5]
    - [/base/joint_states, 1]
  delay: 5