generic_throttle:
  namespace: debug # namespace for republished topics
  framerate: #[topic_name, max_framerate]
    - [/base/joint_states, 10]
    - [/torso_cam3d_down/rgb/image_raw, 1]

#  resolution: # can be implemented for sensor_msgs/Image, sensor_msgs/ PointCloud2, nav_msgs/OccupancyGrid
#    - [/head_cam/image_raw, 2]
