generic_throttle:
  namespace: debug # namespace for republished topics
  topic_framerate: #[topic_name, max_framerate]
    - [/test1, 1]
    - [/test2, 0.5]
  delay: 5 # delay allowed for subscribe topics, if last message is older than that, trow warning

#  resolution: # can be implemented for sensor_msgs/Image, sensor_msgs/ PointCloud2, nav_msgs/OccupancyGrid
#    - [/head_cam/image_raw, 2]