cloud_sources:
  - name: full_cloud_known
    frame_subsample: 1
    point_subsample: 1
    sensor_frame: head_tof_link
    dynamic_publish: false
    static_publish: true
    dynamic_until_static_publish: true
