cloud_sources:
  - name: full_cloud_filtered
    frame_subsample: 1
    point_subsample: 1
    sensor_frame: head_tof_link
    dynamic_publish: true
    static_publish: false
    dynamic_until_static_publish: false
